name: Build and Test

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install --legacy-peer-deps

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install --legacy-peer-deps
          cd ..

      - name: Build frontend
        run: |
          cd frontend
          npm run build
          cd ..

      - name: Build server
        run: npm run build:server

      - name: Run tests (backend)
        run: npm test

      - name: Run tests (frontend)
        run: |
          cd frontend
          npm test
